// State normalization: NSDL uses Census 2011 numeric codes (27 = Maharashtra,
// 24 = Gujarat, … + 36 Telangana / 37 Andhra Pradesh post-bifurcation — verified:
// code order correlates with CDSL volumes and all 37 codes resolve).
// CDSL perm_state is free text: case variants, abbreviations, typos, foreign
// cities and junk. Single source of truth -> embedded SQL CASE via normSql().

export const UNKNOWN = "Unknown";
export const OUTSIDE = "Outside India";
export const OTHER = "Other";

export const CENSUS: Record<string, string> = {
  "01": "Jammu and Kashmir",
  "02": "Himachal Pradesh",
  "03": "Punjab",
  "04": "Chandigarh",
  "05": "Uttarakhand",
  "06": "Haryana",
  "07": "Delhi",
  "08": "Rajasthan",
  "09": "Uttar Pradesh",
  "10": "Bihar",
  "11": "Sikkim",
  "12": "Arunachal Pradesh",
  "13": "Nagaland",
  "14": "Manipur",
  "15": "Mizoram",
  "16": "Tripura",
  "17": "Meghalaya",
  "18": "Assam",
  "19": "West Bengal",
  "20": "Jharkhand",
  "21": "Odisha",
  "22": "Chhattisgarh",
  "23": "Madhya Pradesh",
  "24": "Gujarat",
  "25": "Dadra and Nagar Haveli and Daman and Diu",
  "26": "Dadra and Nagar Haveli and Daman and Diu",
  "27": "Maharashtra",
  "28": "Karnataka",
  "29": "Karnataka",
  "30": "Goa",
  "31": "Lakshadweep",
  "32": "Kerala",
  "33": "Tamil Nadu",
  "34": "Puducherry",
  "35": "Andaman and Nicobar Islands",
  "36": "Telangana",
  "37": "Andhra Pradesh",
  "0": UNKNOWN,
  "00": UNKNOWN,
};

// Keys are pre-cleaned: UPPER, no dots, single spaces, no edge punctuation.
const ALIASES: Record<string, string> = {
  // Uttar Pradesh
  "UTTAR PRADESH": "Uttar Pradesh",
  "UTTARPRADESH": "Uttar Pradesh",
  "UTTAR PARDESH": "Uttar Pradesh",
  "UTTER PRADESH": "Uttar Pradesh",
  UP: "Uttar Pradesh",
  "U P": "Uttar Pradesh",
  // Madhya Pradesh
  "MADHYA PRADESH": "Madhya Pradesh",
  "MADHYAPRADESH": "Madhya Pradesh",
  "MADHY PRADESH": "Madhya Pradesh",
  "MADHAY PRADESH": "Madhya Pradesh",
  "MADHYA PARDESH": "Madhya Pradesh",
  "MADHYA PRADESH (MP)": "Madhya Pradesh",
  "(MP)": "Madhya Pradesh",
  MP: "Madhya Pradesh",
  "M P": "Madhya Pradesh",
  // West Bengal
  "WEST BENGAL": "West Bengal",
  WESTBENGAL: "West Bengal",
  "WEST-BENGAL": "West Bengal",
  "WEST BANGAL": "West Bengal",
  "WSET BENGAL": "West Bengal",
  WB: "West Bengal",
  "W B": "West Bengal",
  "W BENGAL": "West Bengal",
  // Andhra Pradesh
  "ANDHRA PRADESH": "Andhra Pradesh",
  ANDHRAPRADESH: "Andhra Pradesh",
  "ANDHRA PARDESH": "Andhra Pradesh",
  "ANDRA PRADESH": "Andhra Pradesh",
  "ANDRAPRADESH": "Andhra Pradesh",
  AP: "Andhra Pradesh",
  "A P": "Andhra Pradesh",
  // Telangana
  TELANGANA: "Telangana",
  TELNGANA: "Telangana",
  TELENGANA: "Telangana",
  // Odisha
  ODISHA: "Odisha",
  ORISSA: "Odisha",
  ORRISA: "Odisha",
  ORRISA_: "Odisha",
  // Puducherry
  PUDUCHERRY: "Puducherry",
  PONDICHERRY: "Puducherry",
  // Gujarat (+ cities seen as state)
  GUJARAT: "Gujarat",
  GUJRAT: "Gujarat",
  GUAJRAT: "Gujarat",
  GUJART: "Gujarat",
  GUJURAT: "Gujarat",
  GUARAT: "Gujarat",
  AHMEDABAD: "Gujarat",
  MEHSANA: "Gujarat",
  // Maharashtra (+ typos)
  MAHARASHTRA: "Maharashtra",
  MAHARASTRA: "Maharashtra",
  MAHARASTHRA: "Maharashtra",
  MAHARSHATRA: "Maharashtra",
  MAHARSHTRA: "Maharashtra",
  MAHARAHTRA: "Maharashtra",
  MAHARAHSTRA: "Maharashtra",
  MAHARSAHTRA: "Maharashtra",
  MAHRAHTRA: "Maharashtra",
  MAHRASHTRA: "Maharashtra",
  // Rajasthan
  RAJASTHAN: "Rajasthan",
  RAJASHAN: "Rajasthan",
  RAJSTHAN: "Rajasthan",
  RJASTHAN: "Rajasthan",
  RAJASHTHAN: "Rajasthan",
  RAJ: "Rajasthan",
  // Karnataka (+ cities)
  KARNATAKA: "Karnataka",
  KARNATAK: "Karnataka",
  KARANATAKA: "Karnataka",
  KARNATKA: "Karnataka",
  "BANGALORE KARNATAKA": "Karnataka",
  // Tamil Nadu
  "TAMIL NADU": "Tamil Nadu",
  TAMILNADU: "Tamil Nadu",
  TAMILANDU: "Tamil Nadu",
  // Kerala
  KERALA: "Kerala",
  KERLA: "Kerala",
  // Himachal Pradesh
  "HIMACHAL PRADESH": "Himachal Pradesh",
  "HIMACHAL PARDESH": "Himachal Pradesh",
  "H P": "Himachal Pradesh",
  // Jammu and Kashmir
  "JAMMU AND KASHMIR": "Jammu and Kashmir",
  "JAMMU & KASHMIR": "Jammu and Kashmir",
  "JAMMU KASHMIR": "Jammu and Kashmir",
  "J & K": "Jammu and Kashmir",
  "J&K": "Jammu and Kashmir",
  // Dadra and Nagar Haveli and Daman and Diu
  "DADRA-NGR-HVELI-DAMAN-DIU": "Dadra and Nagar Haveli and Daman and Diu",
  "DADRA NGR HVELI DAMAN DIU": "Dadra and Nagar Haveli and Daman and Diu",
  "DADRA & NAGAR HAVELI": "Dadra and Nagar Haveli and Daman and Diu",
  // Andaman and Nicobar Islands
  "ANDAMAN & NICOBAR ISLANDS": "Andaman and Nicobar Islands",
  "ANDAMAN & NICOBAR": "Andaman and Nicobar Islands",
  "ANDAMAN AND NICOBAR": "Andaman and Nicobar Islands",
  "ANDAMAN NICOBAR": "Andaman and Nicobar Islands",
  // Uttarakhand
  UTTARAKHAND: "Uttarakhand",
  UTTRANCHAL: "Uttarakhand",
  UTTRAKHAND: "Uttarakhand",
  DEHRADUN: "Uttarakhand",
  // Chhattisgarh
  CHHATTISGARH: "Chhattisgarh",
  CHATTISGARH: "Chhattisgarh",
  CHHATISHGARH: "Chhattisgarh",
  CHHATISGARH: "Chhattisgarh",
  "CHATTISH GARH": "Chhattisgarh",
  "C G": "Chhattisgarh",
  // Jharkhand
  JHARKHAND: "Jharkhand",
  // Bihar (+ city/typo)
  BIHAR: "Bihar",
  BOHAR: "Bihar",
  // Delhi
  DELHI: "Delhi",
  "NEW DELHI": "Delhi",
  "NCT OF DELHI": "Delhi",
  // Cities used as state
  KOLKATA: "West Bengal",
  UNNAO: "Uttar Pradesh",
  "HYDERABAD TELANGANA": "Telangana",
  // Canonical names map to themselves (case-insensitive safety net)
  "ARUNACHAL PRADESH": "Arunachal Pradesh",
  ASSAM: "Assam",
  CHANDIGARH: "Chandigarh",
  GOA: "Goa",
  HARYANA: "Haryana",
  LADAKH: "Ladakh",
  LAKSHADWEEP: "Lakshadweep",
  MANIPUR: "Manipur",
  MEGHALAYA: "Meghalaya",
  MIZORAM: "Mizoram",
  NAGALAND: "Nagaland",
  PUNJAB: "Punjab",
  SIKKIM: "Sikkim",
  TRIPURA: "Tripura",
};

// Junk -> Unknown (pure numbers handled by regex, not listed).
const JUNK = new Set([
  "",
  ".",
  "-",
  "OTHERS",
  "OTHER",
  "NOT APPLICABLE",
  "UNION TERRITORY",
  "UNION TERRITORIES",
  "INT STATE",
  "INDIA",
]);

// Recognized non-Indian locations -> Outside India (observed values + countries).
const FOREIGN = new Set(
  [
    "DUBAI",
    "ABU DHABI",
    "ABUDHABI",
    "ABU DHBAI",
    "DHABI",
    "SHARJAH",
    "SHARJAH MAIN CITY",
    "SHARJAH EMIRATE",
    "AJMAN",
    "FUJAIRAH",
    "SOHAR",
    "ALAIN",
    "DOHA",
    "AL DOHA",
    "QATAR",
    "OATAR",
    "KUWAIT",
    "MUSCAT",
    "SALMIYA",
    "MANGAF",
    "OMAN",
    "SULATANATE OF OMAN",
    "RIYADH",
    "JEDDAH",
    "AL KHOBAR",
    "ALKHOBAR",
    "MAKKAH",
    "SAUDI ARABIA",
    "SAUDI",
    "BAHRAIN",
    "MANAMA",
    "BUDAIYA",
    "SINGAPORE",
    "SG",
    "LONDON",
    "ENGLAND",
    "GREAT BRITAIN",
    "UNITED KINGDOM",
    "UK",
    "USA",
    "US",
    "UAE",
    "U A E",
    "OUT OF INDIA",
    "HONG KONG",
    "HONGKONG",
    "KOWLOON",
    "TOKYO",
    "YOKOHAMA",
    "TSUKUBA",
    "BANGKOK",
    "BANKOK",
    "KUALA LUMPUR",
    "SELANGOR",
    "THAILAND",
    "CHONBURI",
    "AUSTRALIA",
    "SYDNEY",
    "MELBOURNE",
    "VICTORIA",
    "VIC",
    "NSW",
    "NEW SOUTH WALES",
    "QUEENSLAND",
    "WESTERN AUSTRALIA",
    "CANADA",
    "TORONTO",
    "ONTARIO",
    "ALBERTA",
    "MISSISSAUGA",
    "BRITISH COLUMBIA",
    "SWITZERLAND",
    "BASEL",
    "GENEVA",
    "FRIBOURG",
    "GERMANY",
    "BERLIN",
    "HESSEN",
    "MUNCHEN",
    "FRANKFURT",
    "BAVARIA",
    "DUSSELPORF",
    "INGOLSTADT",
    "ULM",
    "WUPPERTAL",
    "GOTTINGEN",
    "NETHERLAND",
    "NEDERLAND",
    "HOLLAND",
    "AMSTERDAM",
    "ROTTERDAM",
    "UTRECHT",
    "IRELAND",
    "DUBLIN",
    "BELGIUM",
    "BRUSSELS",
    "FRANCE",
    "LUXEMBOURG",
    "ITALY",
    "NEVADA",
    "TEXAS",
    "FLORIDA",
    "CALIFORNIA",
    "NEW YORK",
    "NEW JERSEY",
    "OHIO",
    "GEORGIA",
    "VIRGINIA",
    "ILLINOIS",
    "MASSACHUSETTS",
    "CONNECTICUT",
    "MICHIGAN",
    "WASHINGTON",
    "NORTH CAROLINA",
    "NORTH DAKOTA",
    "IDAHO",
    "TAMPA",
    "HOUSTON",
    "PLANO",
    "IRVING",
    "GRAPEVINE",
    "ROUND ROCK",
    "SUGAR LAND",
    "SUNNYVALE",
    "REDMOND",
    "GILBERT",
    "TROY",
    "INDIANA",
    "NIGERIA",
    "GHANA",
    "KENYA",
    "NAIROBI",
    "TANZANIA",
    "DAR ES SALAAM",
    "SOUTH AFRICA",
    "WESTERN CAPE",
    "BOTSWANA",
    "CONGO",
    "IRAQ",
    "JERUSALEM",
    "JAPAN",
    "NEW ZEALAND",
    "AUCKLAND",
    "MALAYSIA",
    "THAILAND",
    "VIETNAM",
  ].map((s) => s.replace(/\./g, ""))
);

const qlit = (s: string) => `'${s.replace(/'/g, "''")}'`;

function caseSql(col: string, entries: Record<string, string> | Set<string>, then: string): string {
  const keys = entries instanceof Set ? [...entries] : Object.keys(entries);
  const whens = keys
    .map((k) => {
      const v = entries instanceof Set ? then : (entries as Record<string, string>)[k];
      return `WHEN ${qlit(k)} THEN ${qlit(v)}`;
    })
    .join(" ");
  return whens;
}

/** SQL expression -> canonical state name. col = state_code, depo = depository. */
export function normSql(col = "state_code", depo = "depository"): string {
  const clean = `UPPER(REGEXP_REPLACE(REPLACE(TRIM(${col}, ' .,'), '.', ''), '\\s+', ' ', 'g'))`;
  const numCases = Object.entries(CENSUS)
    .map(([k, v]) => `WHEN ${qlit(k)} THEN ${qlit(v)}`)
    .join(" ");
  const aliasCases = caseSql(col, ALIASES, "");
  const junkList = [...JUNK].map(qlit).join(", ");
  const foreignList = [...FOREIGN].map(qlit).join(", ");
  return (
    `(CASE WHEN ${depo} = 'nsdl' THEN ` +
    `(CASE TRIM(${col}) ${numCases} ELSE ${qlit(UNKNOWN)} END) ` +
    `WHEN ${clean} IN (${junkList}) OR ${clean} ~ '^[0-9]+$' THEN ${qlit(UNKNOWN)} ` +
    `WHEN ${clean} IN (${foreignList}) THEN ${qlit(OUTSIDE)} ` +
    `ELSE COALESCE((CASE ${clean} ${aliasCases} END), ${qlit(OTHER)}) END)`
  );
}

export const CANONICAL_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  OUTSIDE,
  UNKNOWN,
  OTHER,
];
